name: Continuous Integration
on: [push, pull_request]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0

    - name: NPM Install
      run: npm install

    - name: ESLint
      run: npx eslint .
